import assert from 'node:assert/strict';
import {emptyRegistry,resolveConfig} from './builder/model.mjs';
import {applyConfig} from './builder/compiler.mjs';
import {buildPrompt} from './builder/prompt.mjs';
import {TAROT_CARDS} from './builder/tarot-cards.mjs';

assert.equal(TAROT_CARDS.length,78);
const config=resolveConfig(emptyRegistry(),{video_preset:'tarot_monthly',layout_preset:'portrait_standard',background:'background.png',overrides:{video:{},layout:{}},ai:{}});
config.tarot={year:2026,month:10,zodiac:'sagittarius',cards:['overall','relationships','work','advice'].map((position,i)=>({position,card_id:TAROT_CARDS[i].id}))};
const scenes=['intro','overall','relationships','work','advice'].map(phase=>({text:`${phase}の原稿`,tarot_phase:phase,...(phase==='intro'?{hook_text:'射手座の10月'}:{})}));
const generated=applyConfig({tarot:{year:1900,cards:[]},scenes},config,null);
assert.equal(generated.global_settings.template,'tarot_monthly');
assert.equal(generated.global_settings.tarot_renderer,undefined);
assert.equal(generated.global_settings.voice_mode,'tts');
assert.equal(generated.tarot.year,2026);
assert.deepEqual(generated.tarot.cards,config.tarot.cards);
assert.ok(generated.tarot.cards.every(card=>!('reading' in card)));
assert.equal(generated.scenes[1].tarot_phase,'overall');
assert.ok(!('audio_file' in generated));
assert.match(buildPrompt(config,scenes.map(s=>s.text).join('。'),null,'content'),/tarot_phase/);
assert.throws(()=>applyConfig({scenes:[...scenes].reverse()},config,null),/順/);
const recorded=structuredClone(config);
recorded.video.voice_mode='anonymous';recorded.video.intro_caption=true;
recorded.video.body_caption=false;recorded.video.intro_visualizer=true;
recorded.video.hook_band_enabled=true;recorded.video.bgm_mode='track';recorded.video.bgm_track='chill';
recorded.ai.hook='manual';recorded.ai.manual_hook='手動のタイトル';
const withAudio=applyConfig({scenes},recorded,{tracks:[{id:'chill',categories:['calm']}]});
assert.equal(withAudio.audio_file,'新規録音.m4a');
assert.equal(withAudio.global_settings.voice_mode,'anonymous');
assert.equal(withAudio.global_settings.bgm.track_id,'chill');
assert.equal(withAudio.scenes[0].hook_text,'手動のタイトル');
assert.equal(withAudio.scenes[0].caption_enabled,true);
assert.equal(withAudio.scenes[0].visualizer,true);
assert.equal(withAudio.scenes[1].caption_enabled,false);
assert.equal(withAudio.scenes[1].visualizer,false);
assert.match(buildPrompt(recorded,'ナレーション',null,'content'),/手動のタイトル/);
const cinematic=resolveConfig(emptyRegistry(),{video_preset:'tarot_monthly_remotion',layout_preset:'portrait_standard',background:'background.png',overrides:{video:{},layout:{}},ai:{}});
cinematic.tarot=structuredClone(config.tarot);
assert.equal(cinematic.video.tarot_renderer,'remotion');
const remotion=applyConfig({scenes},cinematic,null);
assert.equal(remotion.global_settings.tarot_renderer,'remotion');
assert.deepEqual(remotion.tarot,generated.tarot);
assert.deepEqual(remotion.scenes,generated.scenes);
assert.throws(()=>resolveConfig(emptyRegistry(),{video_preset:'tiktok_standard',overrides:{video:{tarot_renderer:'remotion'}}}),/専用/);
console.log('tarot preset, phase order, fixed card results without reading memos: OK');
